// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAction = "action"

// Action mapped from table <action>
type Action struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID     int64     `gorm:"column:user_id;not null;default:9" json:"user_id"`
	Type       string    `gorm:"column:type" json:"type"`
	Describe   string    `gorm:"column:describe;not null" json:"describe"`
	IP         string    `gorm:"column:ip;not null" json:"ip"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Action's table name
func (*Action) TableName() string {
	return TableNameAction
}
