// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAikey = "aikey"

// Aikey mapped from table <aikey>
type Aikey struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Key        string    `gorm:"column:key;not null" json:"key"`
	Host       string    `gorm:"column:host;not null" json:"host"`
	Remarks    string    `gorm:"column:remarks;not null" json:"remarks"`
	Type       string    `gorm:"column:type;not null;comment:openai sd" json:"type"`           // openai sd
	Models     string    `gorm:"column:models;not null;comment:可用模型" json:"models"`            // 可用模型
	Check      int32     `gorm:"column:check;not null;comment:1 检查token可用性 0不检查" json:"check"` // 1 检查token可用性 0不检查
	Limit_     float64   `gorm:"column:limit;not null;comment:总限制" json:"limit"`               // 总限制
	Usage      float64   `gorm:"column:usage;not null;comment:已经使用" json:"usage"`              // 已经使用
	Status     int32     `gorm:"column:status;default:1;comment:1 正常 0异常" json:"status"`       // 1 正常 0异常
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Aikey's table name
func (*Aikey) TableName() string {
	return TableNameAikey
}
