// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCashback = "cashback"

// Cashback mapped from table <cashback>
type Cashback struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID           int64     `gorm:"column:user_id;not null" json:"user_id"`
	BenefitID        int64     `gorm:"column:benefit_id;primaryKey;comment:受益者" json:"benefit_id"`                     // 受益者
	PayAmount        string    `gorm:"column:pay_amount;not null;comment:支付金额（分）" json:"pay_amount"`                   // 支付金额（分）
	CommissionRate   string    `gorm:"column:commission_rate;not null;comment:提成比例（1 - 10000）" json:"commission_rate"` // 提成比例（1 - 10000）
	CommissionAmount string    `gorm:"column:commission_amount;not null;comment:提成金额（分）" json:"commission_amount"`     // 提成金额（分）
	Remarks          string    `gorm:"column:remarks;comment:评论" json:"remarks"`                                       // 评论
	OrderID          int64     `gorm:"column:order_id;not null" json:"order_id"`
	Status           int32     `gorm:"column:status;not null;default:3;comment:0异常 1正常 3审核中 6等待下发" json:"status"` // 0异常 1正常 3审核中 6等待下发
	CreateTime       time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime       time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	IsDelete         int32     `gorm:"column:is_delete;not null" json:"is_delete"`
}

// TableName Cashback's table name
func (*Cashback) TableName() string {
	return TableNameCashback
}
