// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameConfig = "config"

// Config mapped from table <config>
type Config struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;primaryKey" json:"name"`
	Value      string    `gorm:"column:value" json:"value"`
	Remarks    string    `gorm:"column:remarks;not null" json:"remarks"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Config's table name
func (*Config) TableName() string {
	return TableNameConfig
}
