// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDialog = "dialog"

// Dialog mapped from table <dialog>
type Dialog struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Issue      string    `gorm:"column:issue;not null" json:"issue"`
	Answer     string    `gorm:"column:answer" json:"answer"`
	Models     string    `gorm:"column:models;not null" json:"models"`
	Delay      int32     `gorm:"column:delay;not null" json:"delay"`
	Status     int32     `gorm:"column:status;not null" json:"status"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Dialog's table name
func (*Dialog) TableName() string {
	return TableNameDialog
}
