// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDrawRecord = "draw_record"

// DrawRecord mapped from table <draw_record>
type DrawRecord struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID        int64     `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`                   // 用户id
	InsetImageURL string    `gorm:"column:inset_image_url;not null;comment:插入图" json:"inset_image_url"`    // 插入图
	Images        string    `gorm:"column:images;comment:生成图" json:"images"`                               // 生成图
	Prompt        string    `gorm:"column:prompt;not null;comment:生成提示词" json:"prompt"`                    // 生成提示词
	Model         string    `gorm:"column:model;not null;comment:使用模型" json:"model"`                       // 使用模型
	Params        string    `gorm:"column:params;not null;comment:附加参数" json:"params"`                     // 附加参数
	TakeTime      int32     `gorm:"column:take_time;not null;comment:占用时间" json:"take_time"`               // 占用时间
	Size          string    `gorm:"column:size;not null;comment:生成尺寸" json:"size"`                         // 生成尺寸
	Status        int32     `gorm:"column:status;not null;default:1;comment:状态 0被删 1公开 4私有" json:"status"` // 状态 0被删 1公开 4私有
	CreateTime    time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime    time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName DrawRecord's table name
func (*DrawRecord) TableName() string {
	return TableNameDrawRecord
}
