// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInstalledPlugin = "installed_plugin"

// InstalledPlugin mapped from table <installed_plugin>
type InstalledPlugin struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID     int64     `gorm:"column:user_id;not null" json:"user_id"`
	PluginID   int64     `gorm:"column:plugin_id;not null" json:"plugin_id"`
	Status     int32     `gorm:"column:status;not null" json:"status"`
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
	IsDelete   int32     `gorm:"column:is_delete;not null" json:"is_delete"`
}

// TableName InstalledPlugin's table name
func (*InstalledPlugin) TableName() string {
	return TableNameInstalledPlugin
}
