// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID           int64     `gorm:"column:user_id;not null" json:"user_id"`
	Content          string    `gorm:"column:content" json:"content"`
	PersonaID        int64     `gorm:"column:persona_id;not null" json:"persona_id"`
	Role             string    `gorm:"column:role;not null" json:"role"`
	FrequencyPenalty int32     `gorm:"column:frequency_penalty;not null" json:"frequency_penalty"`
	MaxTokens        int32     `gorm:"column:max_tokens;not null" json:"max_tokens"`
	Model            string    `gorm:"column:model;not null" json:"model"`
	PresencePenalty  int32     `gorm:"column:presence_penalty;not null" json:"presence_penalty"`
	Temperature      int32     `gorm:"column:temperature;not null" json:"temperature"`
	ParentMessageID  string    `gorm:"column:parent_message_id;not null;default:0" json:"parent_message_id"`
	Status           int32     `gorm:"column:status;not null;default:1" json:"status"`
	PluginID         int64     `gorm:"column:plugin_id;not null" json:"plugin_id"`
	CreateTime       time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime       time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
