// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "order"

// Order mapped from table <order>
type Order struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TradeNo      string    `gorm:"column:trade_no;not null;comment:支付方订单ID" json:"trade_no"`      // 支付方订单ID
	TradeStatus  string    `gorm:"column:trade_status;not null;comment:支付状态" json:"trade_status"` // 支付状态
	UserID       string    `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`           // 用户ID
	ProductID    int64     `gorm:"column:product_id;not null;comment:商品产品id" json:"product_id"`   // 商品产品id
	ProductTitle string    `gorm:"column:product_title;not null" json:"product_title"`
	ProductInfo  string    `gorm:"column:product_info;comment:商品信息快照" json:"product_info"`             // 商品信息快照
	Money        float64   `gorm:"column:money;not null;comment:支付金额" json:"money"`                    // 支付金额
	PayType      string    `gorm:"column:pay_type;not null;comment:支付方式 wxpay alipay" json:"pay_type"` // 支付方式 wxpay alipay
	PayURL       string    `gorm:"column:pay_url;not null;comment:支付URL" json:"pay_url"`               // 支付URL
	Channel      string    `gorm:"column:channel;not null;comment:渠道号" json:"channel"`                 // 渠道号
	PaymentID    int64     `gorm:"column:payment_id;not null;comment:支付产品ID" json:"payment_id"`        // 支付产品ID
	PaymentInfo  string    `gorm:"column:payment_info;comment:支付产品信息" json:"payment_info"`             // 支付产品信息
	NotifyInfo   string    `gorm:"column:notify_info;comment:通知回来的全部信息" json:"notify_info"`            // 通知回来的全部信息
	Params       string    `gorm:"column:params;comment:拓展参数" json:"params"`                           // 拓展参数
	IP           string    `gorm:"column:ip;not null" json:"ip"`
	CreateTime   time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime   time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
