// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePersona = "persona"

// Persona mapped from table <persona>
type Persona struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      int64     `gorm:"column:user_id;not null" json:"user_id"`
	Title       string    `gorm:"column:title;not null" json:"title"`
	Avatar      string    `gorm:"column:avatar;not null" json:"avatar"`
	Description string    `gorm:"column:description;not null" json:"description"`
	Context     string    `gorm:"column:context;not null" json:"context"`
	Status      int32     `gorm:"column:status;not null;comment:1 正常 0异常 4审核中" json:"status"` // 1 正常 0异常 4审核中
	System      int32     `gorm:"column:system;not null;comment:系统级别的角色" json:"system"`       // 系统级别的角色
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Persona's table name
func (*Persona) TableName() string {
	return TableNamePersona
}
