// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProduct = "product"

// Product mapped from table <product>
type Product struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title         string    `gorm:"column:title;not null" json:"title"`
	Price         int32     `gorm:"column:price;not null" json:"price"`
	OriginalPrice int32     `gorm:"column:original_price;not null" json:"original_price"`
	Value         int32     `gorm:"column:value;not null" json:"value"`
	Badge         string    `gorm:"column:badge;not null" json:"badge"`
	Status        int32     `gorm:"column:status;not null;default:1;comment:1为正常" json:"status"`              // 1为正常
	Type          string    `gorm:"column:type;not null;comment:integral 或 day" json:"type"`                  // integral 或 day
	Level         int32     `gorm:"column:level;not null;default:1;comment:会员级别 1 普通 2会员 3超级会员" json:"level"` // 会员级别 1 普通 2会员 3超级会员
	Describe      string    `gorm:"column:describe;not null;comment:描述" json:"describe"`                      // 描述
	Sort          int32     `gorm:"column:sort;not null;comment:排序" json:"sort"`                              // 排序
	CreateTime    time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime    time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
