// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReward = "reward"

// Reward mapped from table <reward>
type Reward struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:奖励表" json:"id"` // 奖励表
	Category   string    `gorm:"column:category;not null;comment:签到 ｜ 邀请" json:"category"`      // 签到 ｜ 邀请
	Value      string    `gorm:"column:value;not null" json:"value"`
	Type       string    `gorm:"column:type;not null;comment:天 ｜ 积分" json:"type"`              // 天 ｜ 积分
	Demand     string    `gorm:"column:demand;not null;comment:要求 签到是连续 邀请是不连续" json:"demand"` // 要求 签到是连续 邀请是不连续
	Status     int32     `gorm:"column:status;not null;default:1;comment:1有效" json:"status"`   // 1有效
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Reward's table name
func (*Reward) TableName() string {
	return TableNameReward
}
