// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTurnover = "turnover"

// Turnover mapped from table <turnover>
type Turnover struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID     int64     `gorm:"column:user_id;not null;comment:用户" json:"user_id"`   // 用户
	Describe   string    `gorm:"column:describe;not null;comment:描述" json:"describe"` // 描述
	Value      string    `gorm:"column:value;not null;comment:值" json:"value"`        // 值
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	IsDelete   int32     `gorm:"column:is_delete;not null" json:"is_delete"`
}

// TableName Turnover's table name
func (*Turnover) TableName() string {
	return TableNameTurnover
}
