// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUploadRecord = "upload_record"

// UploadRecord mapped from table <upload_record>
type UploadRecord struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID       int64     `gorm:"column:user_id;not null" json:"user_id"`
	Mimetype     string    `gorm:"column:mimetype;not null" json:"mimetype"`
	Sha1         string    `gorm:"column:sha1;not null" json:"sha1"`
	Md5          string    `gorm:"column:md5;not null" json:"md5"`
	URL          string    `gorm:"column:url;not null" json:"url"`
	Originalname string    `gorm:"column:originalname;not null" json:"originalname"`
	Name         string    `gorm:"column:name;not null" json:"name"`
	Type         string    `gorm:"column:type;not null" json:"type"`
	Size         string    `gorm:"column:size;not null" json:"size"`
	Status       int32     `gorm:"column:status;not null;default:1" json:"status"`
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	IsDelete     int32     `gorm:"column:is_delete;not null" json:"is_delete"`
}

// TableName UploadRecord's table name
func (*UploadRecord) TableName() string {
	return TableNameUploadRecord
}
