// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Nickname       string    `gorm:"column:nickname;not null" json:"nickname"`
	Account        string    `gorm:"column:account;not null" json:"account"`
	Password       string    `gorm:"column:password;not null" json:"password"`
	Avatar         string    `gorm:"column:avatar;not null" json:"avatar"`
	Role           string    `gorm:"column:role;not null" json:"role"`
	Integral       int32     `gorm:"column:integral;not null" json:"integral"`
	VipExpireTime  time.Time `gorm:"column:vip_expire_time;not null;default:2000-01-01 00:00:00;comment:会员时间" json:"vip_expire_time"`     // 会员时间
	SvipExpireTime time.Time `gorm:"column:svip_expire_time;not null;default:2000-01-01 00:00:00;comment:超级会员时间" json:"svip_expire_time"` // 超级会员时间
	Status         int32     `gorm:"column:status;not null;default:1;comment:1正常" json:"status"`                                          // 1正常
	IP             string    `gorm:"column:ip;not null" json:"ip"`
	InviteCode     string    `gorm:"column:invite_code;not null;comment:邀请码" json:"invite_code"`             // 邀请码
	SuperiorID     int64     `gorm:"column:superior_id;not null;comment:上级ID（一旦确定将不可修改）" json:"superior_id"` // 上级ID（一旦确定将不可修改）
	UserAgent      string    `gorm:"column:user_agent;comment:ua" json:"user_agent"`                         // ua
	CreateTime     time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime     time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
